### ISSUE TITLE
unexpected keyword argument 'metavar'

### ISSUE THREAD

**Issue by drandreaskrueger** [chriskiehl/GooeyExamples#1]
```
Traceback (most recent call last):
  File "GooeyExamples\examples\simple_demo.py", line 30, in <module>
    main()
  File "gooey\python_bindings\gooey_decorator.py", line 58, in inner2
    return payload(*args, **kwargs)
  File "GooeyExamples\examples\simple_demo.py", line 24, in main
    help='I turn things on and off')
  File "gooey\python_bindings\gooey_parser.py", line 28, in add_argument
    self.parser.add_argument(*args, **kwargs)
  File "C:\Anaconda\lib\argparse.py", line 1294, in add_argument
    action = action_class(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'metavar'
```

with today's clone of /GooeyExamples, and this version

```
pip install gooey
import gooey
print gooey.__version__
```

0.8.11.1

**Comment by drandreaskrueger** [comment]
ah ...

    pip uninstall gooey

    git clone https://github.com/chriskiehl/Gooey.git
    python setup.py install

    import gooey
    print gooey.__version__

0.9.2

Now the examples are working, without that error above. Superb. Thanks.

--> The version via pip needs to be updated.

**Comment by chriskiehl** [comment]
pip has since been updated ^_^
