### ISSUE TITLE
dynamic_updates.py doesn't run

### ISSUE THREAD

**Issue by edjw** [chriskiehl/GooeyExamples#10]
Python3

```
Traceback (most recent call last):
  File "dynamic_updates.py", line 110, in <module>
    main()
  File "/usr/local/lib/python3.6/site-packages/gooey/python_bindings/gooey_decorator.py", line 83, in inner2
    return payload(*args, **kwargs)
  File "dynamic_updates.py", line 53, in main
    args = parser.parse_args()
  File "/usr/local/lib/python3.6/site-packages/gooey/python_bindings/gooey_parser.py", line 113, in parse_args
    return self.parser.parse_args(args, namespace)
  File "/usr/local/lib/python3.6/site-packages/gooey/python_bindings/gooey_decorator.py", line 78, in run_gooey
    application.run(build_spec)
  File "/usr/local/lib/python3.6/site-packages/gooey/gui/application.py", line 15, in run
    app = build_app(build_spec)
  File "/usr/local/lib/python3.6/site-packages/gooey/gui/application.py", line 24, in build_app
    gapp = GooeyApplication(merge(build_spec, imagesPaths))
  File "/usr/local/lib/python3.6/site-packages/gooey/gui/containers/application.py", line 65, in __init__
    self.fetchExternalUpdates()
  File "/usr/local/lib/python3.6/site-packages/gooey/gui/containers/application.py", line 150, in fetchExternalUpdates
    self.buildSpec['encoding']
  File "/usr/local/lib/python3.6/site-packages/gooey/gui/seeder.py", line 15, in fetchDynamicProperties
    proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: "'/usr/local/opt/python3/bin/python3.6' -u 'dynamic_updates.py' gooey-seed-ui --ignore-gooey": "'/usr/local/opt/python3/bin/python3.6' -u 'dynamic_updates.py' gooey-seed-ui --ignore-gooey"
```

Python 2

```
Traceback (most recent call last):
  File "dynamic_updates.py", line 108, in <module>
    main()
  File "/Library/Python/2.7/site-packages/gooey/python_bindings/gooey_decorator.py", line 83, in inner2
    return payload(*args, **kwargs)
  File "dynamic_updates.py", line 53, in main
    args = parser.parse_args()
  File "/Library/Python/2.7/site-packages/gooey/python_bindings/gooey_parser.py", line 113, in parse_args
    return self.parser.parse_args(args, namespace)
  File "/Library/Python/2.7/site-packages/gooey/python_bindings/gooey_decorator.py", line 78, in run_gooey
    application.run(build_spec)
  File "/Library/Python/2.7/site-packages/gooey/gui/application.py", line 15, in run
    app = build_app(build_spec)
  File "/Library/Python/2.7/site-packages/gooey/gui/application.py", line 24, in build_app
    gapp = GooeyApplication(merge(build_spec, imagesPaths))
  File "/Library/Python/2.7/site-packages/gooey/gui/containers/application.py", line 65, in __init__
    self.fetchExternalUpdates()
  File "/Library/Python/2.7/site-packages/gooey/gui/containers/application.py", line 150, in fetchExternalUpdates
    self.buildSpec['encoding']
  File "/Library/Python/2.7/site-packages/gooey/gui/seeder.py", line 15, in fetchDynamicProperties
    proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by chriskiehl** [comment]
which OS and Gooey Version?

**Comment by chriskiehl** [comment]
Disregard above. After actually looking at your stack trace I realized thar be OSX paths.

Looks like this is a cross-platform quirk in Gooey itself. Adding `shell=True` in `gooey/gui/seeders.py` Popen call fixes this issue. I don't quite know why it fails on OSX but works on everything else. Could you open this issue under the main Gooey project?   

i'm going to close the one here as it's not an issue with the demo code.
