### ISSUE TITLE
TypeError: Font(): arguments did not match any overloaded call

### ISSUE THREAD

**Issue by kdaily** [chriskiehl/GooeyExamples#7]
Running [examples/simple_demo.py](https://github.com/chriskiehl/GooeyExamples/blob/master/examples/simple_demo.py):

```
python simple_demo.py 
Traceback (most recent call last):
  File "simple_demo.py", line 28, in <module>
    main()
  File "/usr/lib/python2.7/site-packages/Gooey-0.9.2.5-py2.7.egg/gooey/python_bindings/gooey_decorator.py", line 71, in inner2
    return payload(*args, **kwargs)
  File "simple_demo.py", line 24, in main
    args = parser.parse_args()
  File "/usr/lib/python2.7/site-packages/Gooey-0.9.2.5-py2.7.egg/gooey/python_bindings/gooey_parser.py", line 59, in parse_args
    return self.parser.parse_args(args, namespace)
  File "/usr/lib/python2.7/site-packages/Gooey-0.9.2.5-py2.7.egg/gooey/python_bindings/gooey_decorator.py", line 66, in run_gooey
    application.run(build_spec)
  File "/usr/lib/python2.7/site-packages/Gooey-0.9.2.5-py2.7.egg/gooey/gui/application.py", line 19, in run
    controller = Controller(build_spec)
  File "/usr/lib/python2.7/site-packages/Gooey-0.9.2.5-py2.7.egg/gooey/gui/controller.py", line 10, in __init__
    self.view = BaseWindow(layout_type=self.model.layout_type)
  File "/usr/lib/python2.7/site-packages/Gooey-0.9.2.5-py2.7.egg/gooey/gui/windows/base_window.py", line 42, in __init__
    self._init_components()
  File "/usr/lib/python2.7/site-packages/Gooey-0.9.2.5-py2.7.egg/gooey/gui/windows/base_window.py", line 110, in _init_components
    self.head_panel = header.FrameHeader(parent=self)
  File "/usr/lib/python2.7/site-packages/Gooey-0.9.2.5-py2.7.egg/gooey/gui/windows/header.py", line 29, in __init__
    self._init_components()
  File "/usr/lib/python2.7/site-packages/Gooey-0.9.2.5-py2.7.egg/gooey/gui/windows/header.py", line 54, in _init_components
    self._header = wx_util.h1(self, '')
  File "/usr/lib/python2.7/site-packages/Gooey-0.9.2.5-py2.7.egg/gooey/gui/util/wx_util.py", line 26, in h1
    return _header(parent, label, (wx.FONTFAMILY_DEFAULT, wx.FONTWEIGHT_NORMAL, wx.FONTWEIGHT_BOLD, False))
  File "/usr/lib/python2.7/site-packages/Gooey-0.9.2.5-py2.7.egg/gooey/gui/util/wx_util.py", line 34, in _header
    font = wx.Font(font_size * 1.2, *styles)
TypeError: Font(): arguments did not match any overloaded call:
  overload 1: too many arguments
  overload 2: argument 1 has unexpected type 'float'
  overload 3: argument 1 has unexpected type 'float'
  overload 4: argument 3 has unexpected type 'FontWeight'
  overload 5: argument 1 has unexpected type 'float'
  overload 6: argument 1 has unexpected type 'float'
  overload 7: argument 1 has unexpected type 'float'
```

**Comment by chriskiehl** [comment]
resolved in latest Gooey version (currently 1.0.1)
